AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  S3BucketName:
    Description: Type of this BacketName.
    Type: String
  ApplicationUrl:
    Description: The URL of your application
    Type: String
    Default: 'https://example.com'

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - !Ref ApplicationUrl
            Id: myCORSRuleId1
            MaxAge: 3600
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - 'http://localhost:3000'
            Id: myCORSRuleId2
            MaxAge: 1800
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3Bucket
              - /*
          Principal: "*"
          Condition:
            StringLike:
              'aws:Referer':
                - !Join
                  - ''
                  - - !Ref ApplicationUrl
                    - /*
                - 'http://localhost:3000/*'
